export default [
  {
    id: 1,
    price: 500.0,
    title: "white wooden dining table set",
    img: "../images/accessories1.png",
    star_className: "fa-solid fa-star",
    cart_className: "fa-solid fa-cart-shopping",
    category: "Accessories",
    brand: "Ikea",
    quantity: 1,
  },
  {
    id: 2,
    price: 700.0,
    title: "throw pillow on bed frame",
    img: "../images/accessories2.png",
    quantity: 1,
    star_className: "fa-solid fa-star",
    cart_className: "fa-solid fa-cart-shopping",
    category: "Beds",
    brand: "Amendo",
  },

  // {
  //   id: 2,
  //   title: "Moto G5 Plus",
  //   price: 600.0,
  //   img: "https://res.cloudinary.com/drecbsopp/image/upload/v1627398477/MotoGPowerDual_2021_Reformatted_1_330x_wp8gve.png",
  //   quantity: 1,
  // },
  // {
  //   id: 3,
  //   title: "Xiaomi Redmi Note 2",
  //   price: 500.0,
  //   img: "https://res.cloudinary.com/drecbsopp/image/upload/v1627398543/D7A7DA95-AEF8-228B-A2D2-A3FEBF237C33_y9p6wq.png",
  //   quantity: 1,
  // },
  // {
  //   id: 4,
  //   title: "Nokia G20",
  //   price: 400.0,
  //   img: "https://res.cloudinary.com/drecbsopp/image/upload/v1627398698/nokia3_resize_md_qdw7bv.jpg",
  //   quantity: 1,
  // },
  // {
  //   id: 5,
  //   title: "Apple i phone",
  //   price: 4000.0,
  //   img: "https://www.91-img.com/gallery_images_uploads/3/d/3df5ca6a9b470f715b085991144a5b76e70da975.JPG?tr=h-550,w-0,c-at_max",
  //   quantity: 1,
  // },

  {
    id: 3,
    price: 700.0,
    title: "throw pillow on bed frame",
    img: "../images/bed1.png",
    quantity: 1,
  },

  {
    id: 4,
    price: 700.0,
    title: "black chair on white snow",
    img: "../images/chair6.png",
    star_className: "fa-solid fa-star",
    cart_className: "fa-solid fa-cart-shopping",
    category: "Chairs",
    brand: "Ikea",
    quantity: 1,
  },
  {
    id: 5,
    price: 700.0,
    title: "brown and gray table and chair set",
    img: "../images/table4.png",
    star_className: "fa-solid fa-star",
    cart_className: "fa-solid fa-cart-shopping",
    category: "Tables",
    brand: "Amendo",
    quantity: 1,
  },
  {
    id: 6,
    price: 700.0,
    title: "white wooden dining table set",
    img: "../images/accessories1.png",
    star_className: "fa-solid fa-star",
    cart_className: "fa-solid fa-cart-shopping",
    category: "Accessories",
    brand: "Ikea",
    quantity: 1,
  },
  {
    id: 7,
    price: 700.0,
    title: "a chair and a table in a room",
    img: "../images/furniture1.png",
    star_className: "fa-solid fa-star",
    cart_className: "fa-solid fa-cart-shopping",
    category: "Furniture",
    brand: "The Factory",
    quantity: 1,
  },
  {
    id: 8,
    price: 700.0,
    title: "gray pedded chair",
    img: "../images/homeDeco1.png",
    star_className: "fa-solid fa-star",
    cart_className: "fa-solid fa-cart-shopping",
    category: "Home Deco",
    brand: "Amendo",
    quantity: 1,
  },
  {
    id: 9,
    price: 700.0,
    title: "brown wooden table with chair",
    img: "../images/dressing1.png",
    star_className: "fa-solid fa-star",
    cart_className: "fa-solid fa-cart-shopping",
    category: "Dressings",
    brand: "Amendo",
    quantity: 1,
  },
  {
    id: 10,
    price: 700.0,
    title: "tufted white upholstered bed",
    img: "../images/bed2.png",
    star_className: "fa-solid fa-star",
    cart_className: "fa-solid fa-cart-shopping",
    category: "Beds",
    brand: "Amendo",
    quantity: 1,
  },

  {
    id: 11,
    price: 700.0,
    title: "white and brown floral bed linen",
    img: "../images/bed4.png",
    star_className: "fa-solid fa-star",
    cart_className: "fa-solid fa-cart-shopping",
    category: "Beds",
    brand: "Amendo",
    quantity: 1,
  },
  {
    id: 12,
    price: 700.0,
    title: "white bed linen on bed",
    img: "../images/bed5.png",
    star_className: "fa-solid fa-star",
    cart_className: "fa-solid fa-cart-shopping",
    category: "Beds",
    brand: "The Factory",
    quantity: 1,
  },
  {
    id: 13,
    price: 80,
    title: "white bedspread and black wooden bed",
    img: "../images/bed6.png",
    star_className: "fa-solid fa-star",
    cart_className: "fa-solid fa-cart-shopping",
    category: "Beds",
    brand: "Ikea",
    quantity: 1,
  },

  {
    id: 14,
    price: 80,
    title: "gray and white pedded chair",
    img: "../images/chair7.png",
    quantity: 1,

    star_className: "fa-solid fa-star",
    cart_className: "fa-solid fa-cart-shopping",
    category: "Chairs",
    brand: "The Factory",
  },
  {
    id: 15,
    price: 80,
    quantity: 1,

    title: "oval white wooden table with chairs",
    img: "../images/chair8.png",
    star_className: "fa-solid fa-star",
    cart_className: "fa-solid fa-cart-shopping",
    category: "Chairs",
    brand: "Ikea",
  },
  {
    id: 16,
    price: 80,
    quantity: 1,

    title: "brown wooden chair beside plant",
    img: "../images/chair9.png",
    star_className: "fa-solid fa-star",
    cart_className: "fa-solid fa-cart-shopping",
    category: "Chairs",
    brand: "Artdeco",
  },
  {
    id: 17,
    price: 80,
    quantity: 1,

    title: "white and black chair beside white table",
    img: "../images/chair10.png",
    star_className: "fa-solid fa-star",
    cart_className: "fa-solid fa-cart-shopping",
    category: "Chairs",
    brand: "Artdeco",
  },
  {
    id: 18,
    price: 80,
    quantity: 1,

    title: "kitchen accessories",
    img: "../images/accessories2.png",
    star_className: "fa-solid fa-star",
    cart_className: "fa-solid fa-cart-shopping",
    category: "Accessories",
    brand: "Artdeco",
  },
  {
    id: 19,
    price: 80,
    quantity: 1,

    title: "brown wooden round table with chairs",
    img: "../images/accessories3.png",
    star_className: "fa-solid fa-star",
    cart_className: "fa-solid fa-cart-shopping",
    category: "Accessories",
    brand: "Ikea",
  },
  {
    id: 20,
    price: 80,
    quantity: 1,

    title: "green plant on white ceramic plot",
    img: "../images/accessories4.png",
    star_className: "fa-solid fa-star",
    cart_className: "fa-solid fa-cart-shopping",
    category: "Accessories",
    brand: "Artdeco",
  },
  {
    id: 21,
    price: 80,
    quantity: 1,

    title: "brown wooden wall mounted cabinet",
    img: "../images/furniture5.png",
    star_className: "fa-solid fa-star",
    cart_className: "fa-solid fa-cart-shopping",
    category: "Furniture",
    brand: "Ikea",
  },
  {
    id: 22,
    price: 80,
    title: "dining table set beside glass window",
    img: "../images/accessories5.png",
    quantity: 1,

    star_className: "fa-solid fa-star",
    cart_className: "fa-solid fa-cart-shopping",
    category: "Accessories",
    brand: "Furniture Inc",
  },
  {
    id: 23,
    price: 80,
    title: "brown wooden bed frame",
    img: "../images/accessories6.png",
    star_className: "fa-solid fa-star",
    quantity: 1,

    cart_className: "fa-solid fa-cart-shopping",
    category: "Accessories",
    brand: "Artdeco",
  },

  {
    id: 24,
    price: 80,
    title: "brown wooden table and chair",
    img: "../images/furniture2.png",
    quantity: 1,

    star_className: "fa-solid fa-star",
    cart_className: "fa-solid fa-cart-shopping",
    category: "Furniture",
    brand: "Furniture Inc",
  },
  {
    id: 25,
    price: 80,
    title: "brown wooden table with chair",
    img: "../images/furniture3.png",
    quantity: 1,

    star_className: "fa-solid fa-star",
    cart_className: "fa-solid fa-cart-shopping",
    category: "Furniture",
    brand: "Furniture Inc",
  },

  {
    id: 26,
    price: 80,
    title: "books on table",
    img: "../images/table3.png",
    quantity: 1,

    star_className: "fa-solid fa-star",
    cart_className: "fa-solid fa-cart-shopping",
    category: "Tables",
    brand: "Furniture Inc",
  },
  {
    id: 27,
    price: 80,
    title: "empty brown wooden stools",
    img: "../images/furniture4.png",
    quantity: 1,

    star_className: "fa-solid fa-star",
    cart_className: "fa-solid fa-cart-shopping",
    category: "Furniture",
    brand: "Artdeco",
  },

  {
    id: 28,
    price: 80,
    title: "brown wooden chairs and table",
    img: "../images/homeDeco2.png",
    star_className: "fa-solid fa-star",
    quantity: 1,

    cart_className: "fa-solid fa-cart-shopping",
    category: "Home Deco",
    brand: "Furniture Inc",
  },
  {
    id: 29,
    price: 80,
    title: "home decoration",
    quantity: 1,

    img: "../images/homeDeco3.png",
    star_className: "fa-solid fa-star",
    cart_className: "fa-solid fa-cart-shopping",
    category: "Home Deco",
    brand: "Artdeco",
  },
  {
    id: 30,
    price: 80,
    title: "snake plant on table",
    img: "../images/table5.png",
    quantity: 1,

    star_className: "fa-solid fa-star",
    cart_className: "fa-solid fa-cart-shopping",
    category: "Tables",
    brand: "Furniture Inc",
  },
  {
    id: 31,
    price: 80,
    title: "black dining set near white wall",
    img: "../images/homeDeco4.png",
    quantity: 1,

    star_className: "fa-solid fa-star",
    cart_className: "fa-solid fa-cart-shopping",
    category: "Home Deco",
    brand: "The Factory",
  },
  {
    id: 32,
    price: 80,
    title: "blue and white bed linen",
    img: "../images/bed3.png",
    quantity: 1,

    star_className: "fa-solid fa-star",
    cart_className: "fa-solid fa-cart-shopping",
    category: "Beds",
    brand: "Furniture Inc",
  },
  {
    id: 33,
    price: 80,
    title: "pink and white wooden kitchen cabinet",
    img: "../images/dressing2.png",
    quantity: 1,

    star_className: "fa-solid fa-star",
    cart_className: "fa-solid fa-cart-shopping",
    category: "Dressings",
    brand: "Furniture Inc",
  },

  {
    id: 34,
    price: 80,
    title: "table set with plates and silverware",
    img: "../images/table1.png",
    quantity: 1,

    star_className: "fa-solid fa-star",
    cart_className: "fa-solid fa-cart-shopping",
    category: "Tables",
    brand: "The Factory",
  },
  {
    id: 35,
    price: 80,
    title: "macbook pro on brown wooden table",
    img: "../images/table2.png",
    quantity: 1,

    star_className: "fa-solid fa-star",
    cart_className: "fa-solid fa-cart-shopping",
    category: "Tables",
    brand: "The Factory",
  },

  {
    id: 36,
    price: 80,
    title: "brown wooden display cabinet",
    img: "../images/dressing3.png",
    quantity: 1,

    star_className: "fa-solid fa-star",
    cart_className: "fa-solid fa-cart-shopping",
    category: "Dressings",
    brand: "The Factory",
  },
];
